export default {
  a: "#FBDB65",
  b: "#BEDBBF",
  c: "#F7F7F7",
  d: "#EBEBEB",
  e: "#FBDB65",
  f: "#BEDBBF",
  g: "#F7F7F7",
  h: "#EBEBEB",
  i: "#FBDB65",
  j: "#BEDBBF",
  k: "#F7F7F7",
  l: "#EBEBEB",
  m: "#FBDB65",
  n: "#BEDBBF",
  o: "#F7F7F7",
  p: "#EBEBEB",
  q: "#FBDB65",
  r: "#BEDBBF",
  s: "#F7F7F7",
  t: "#EBEBEB",
  u: "#FBDB65",
  v: "#BEDBBF",
  w: "#F7F7F7",
  x: "#EBEBEB",
  y: "#FBDB65",
  z: "#BEDBBF",
};
